<a href="https://colab.research.google.com/github/hyphen-ani/Deep-Learning-Pytorch/blob/main/Deep_Learning_Pytorch_Fundaementals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundaementals

In [10]:
import torch
import pandas as pd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [11]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Tensor's In Pytorch -- Introduction

### Creating a tensor, scalar and vectors
#### Created using `torch.tensor()`

In [12]:
# Scalar

scalar = torch.tensor(2)
print()
print("Dimention of Scalar : ", scalar.ndim)
scalar.item()
print('Scalar Shape : ', scalar.shape)


Dimention of Scalar :  0
Scalar Shape :  torch.Size([])


In [13]:
# Vector

vector = torch.tensor([7, 5])
print(vector)
print('Dimension Of Vector : ', vector.ndim)
print('Vector Shape : ', vector.shape)

tensor([7, 5])
Dimension Of Vector :  1
Vector Shape :  torch.Size([2])


In [14]:
# MATRIX

MATRIX = torch.tensor([[4, 5], [6, 7]])
print(MATRIX)
print('Dimension Of Matrix : ', MATRIX.shape)
print('Matrix Shape : ', MATRIX.shape)
MATRIX[1]

tensor([[4, 5],
        [6, 7]])
Dimension Of Matrix :  torch.Size([2, 2])
Matrix Shape :  torch.Size([2, 2])


tensor([6, 7])

In [15]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [4, 5, 6],
                        [4, 6, 7]],

                        [[7, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [4, 5, 6],
                        [5, 6, 7]]])
print(TENSOR)
print('Dimension of Tensor : ', TENSOR.ndim)
print('Tensor Shape : ', TENSOR.shape)
TENSOR[1]


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [4, 5, 6],
         [4, 6, 7]],

        [[7, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [4, 5, 6],
         [5, 6, 7]]])
Dimension of Tensor :  3
Tensor Shape :  torch.Size([2, 5, 3])


tensor([[7, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [4, 5, 6],
        [5, 6, 7]])

## Random Tensors

### Why Random Tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with RN -> Look at data -> Update RN -> look at data -> Update RN`

In [16]:
# Create a RANDOM_TENSOR of size (3, 4)

RANDOM_TENSOR = torch.rand(3, 5)
RANDOM_TENSOR

tensor([[0.7556, 0.2023, 0.7828, 0.7795, 0.1961],
        [0.0126, 0.7827, 0.3007, 0.5116, 0.7145],
        [0.2307, 0.4808, 0.6682, 0.9458, 0.3113]])

In [17]:
# Create a RANDOM_TENSOR with similar shape to an image tensor

RANDOM_IMG_SIZE_TENSOR = torch.rand(size=(224, 224, 3)) #  Represents --> (Height, Width, Color Channels (RGB))
RANDOM_IMG_SIZE_TENSOR.ndim

3

### Zeroes & Ones

In [18]:
# Create a tensor of all zerores

zeros = torch.zeros(size=(3, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones

ones = torch.ones(size=(3, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creating Range of Tensors

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [20]:
# torch.range()

one_to_fifty = torch.arange(start=0, end=51, step=2)
one_to_fifty

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50])

In [21]:
# Creating Tensors Like

fifty_zeroes = torch.zeros_like(one_to_fifty)
fifty_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

### Tensor Datatypes

In [22]:
# Float 32 Tensor

float_32_tensor = torch.tensor([3.0, 6.0, 7.0],
                               dtype=None,  # What datatype is the tensor (float32, float64)
                               device=None, # CPU(cpu) or GPU(cuda), Default: CPU
                               requires_grad=False) # Track Gradients With Tensor Operations
float_32_tensor

tensor([3., 6., 7.])

In [23]:
float_16_tensor = torch.tensor([4.5, 4.4, 2.4],
                               dtype=torch.float16)
float_16_tensor

tensor([4.5000, 4.3984, 2.4004], dtype=torch.float16)

In [24]:
# Change datatype Explicitly

float_changed = float_32_tensor.type(torch.float16)
float_changed

tensor([3., 6., 7.], dtype=torch.float16)

In [25]:
# Multiply Tensors

float_32_tensor * float_16_tensor

tensor([13.5000, 26.3906, 16.8027])

### Getting Information from tensors


1. Tensors datatype `tensor.dtype`
2. Tensors shape `tensor.shape`
3. Tensors device `tensor.device`


In [26]:
INFO_TENSOR = torch.rand((3, 5),dtype=torch.float,device=None,requires_grad=False)

In [27]:
# Details of above Tensors

print(f"Datatype :  {INFO_TENSOR.dtype}")
print('Shape : ' , INFO_TENSOR.shape)
print('Device :  ', INFO_TENSOR.device)

Datatype :  torch.float32
Shape :  torch.Size([3, 5])
Device :   cpu


### Mamipulating Tensors (Tensors Operation)

## Tensors operations include
* Addition
* Substraction
* Multiplication (Element Wise)
* Division
* Matrix Multiplication

In [28]:
# Addition

x_tensor = torch.tensor([1, 2, 3])
x_tensor + 10

tensor([11, 12, 13])

In [29]:
# Multiply

x_tensor * 10

# Substraction

x_tensor - 10

tensor([-9, -8, -7])

In [30]:
# Pytorch - Inbuilt Function

torch.mul(x_tensor, 40)
torch.add(x_tensor, 10)
torch.sub(x_tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-Wise Multiplication
2. Matrix Multiplication

Two rules that need to be satisfied

1. The **inner dimention** must match:
* `(3, 2) @ (3, 2)` -> wont work
* `(3, 2) @ (2, 3)` -> will work

2. The resulting matrix has the shape of the **outer dimention**

* `(3, 2) @ (2, 3)` -> (3, 3)
* `(2, 3) @ (3, 2)` -> (2, 2)

In [31]:
# Element Wise Multiplication

print(x_tensor * x_tensor)

tensor([1, 4, 9])


In [32]:
# Matrix Multiplication

%%time
torch.matmul(x_tensor, x_tensor)

CPU times: user 611 µs, sys: 1.11 ms, total: 1.72 ms
Wall time: 10.7 ms


tensor(14)

In [33]:
%%time

value = 0

for i in range(len(x_tensor)):
  value += x_tensor[i] * x_tensor[i]

print(value)

tensor(14)
CPU times: user 3.89 ms, sys: 0 ns, total: 3.89 ms
Wall time: 4.2 ms


### Common Errors Is Shape Errors

In [34]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

# tensor_B = torch.tensor([[7, 8, 9], -> this works as well
#                         [10, 11, 12]])

tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [35]:
### To fix our tensor issues we can manipulate the tensor using transpose

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [36]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation - Min, Max, Mean, Sum etc.

In [37]:
x = torch.arange(0, 100, 10, dtype=torch.float64)

# Find max
torch.max(x)

# Find min
torch.min(x)

tensor(0., dtype=torch.float64)

In [38]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x)

tensor(45., dtype=torch.float64)

In [39]:
torch.sum(x)

tensor(450., dtype=torch.float64)

In [40]:
### Finding the postion of min and max : Return the position of tensor with min or max value


x.argmin(), x.argmax()

(tensor(0), tensor(9))

### Reshaping, Stacking, Squeezing & Unsqueezing Tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or (hstack)
* Squeez - removes all `1` dimentions from a tensor
* Unsqueez - adds a `1` dimention to a tensor
* Permute - Return a view of the input with dimentions permuted (swaped) in a certain way

In [41]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [42]:
# Reshape

x_reshape = x.reshape(1, 10)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [43]:
# Change View

z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [44]:
# Stack Tensors

x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [45]:
# Squeeze

x_squezed = x_reshape.squeeze()

In [46]:
# UnSqueeze

x_squezed.unsqueeze(dim=0).shape

torch.Size([1, 10])

In [47]:
# Permute  Rearranges Dimentions -> Used mostly in Images

x_original = torch.rand(size=(224, 225, 3))

# Permuting

x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}")

Previous shape : torch.Size([224, 225, 3])
New shape : torch.Size([3, 224, 225])


In [48]:
x_original[0, 0 ,0] = 88475

In [49]:
x_permuted[0, 0, 0]

tensor(88475.)

### Indexing

Indexing with pytorch is similar to numpy

In [50]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
# Indexing

x[0] # First Bracket
x[0, 0] # Second Bracket
x[0, 2, 2] # Third Bracket

tensor(9)

In [52]:
# You can use ":" to select all of the target dimention

x[:, :, 0]
x[:, 1, 1]
x[0, 0, :]
x[:, 2, 2]
x[:, :, 2]

tensor([[3, 6, 9]])

### Pytorch Tensors & Numpy

* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`

In [53]:
# Numpy - Tensor

array = np.arange(1., 8.)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [54]:
# Change the value of array

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [55]:
# Tensor - Numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [58]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7645, 0.9967, 0.4195, 0.8367],
        [0.4532, 0.5326, 0.0481, 0.2350],
        [0.3040, 0.2804, 0.3040, 0.5061]])
tensor([[0.7805, 0.4845, 0.4523, 0.3594],
        [0.1106, 0.5444, 0.4528, 0.3796],
        [0.0968, 0.5403, 0.0558, 0.4103]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [63]:
# Let's Make some random but reproducible tensors

import torch

# Set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
